kind: Template
apiVersion: v1
objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ${NAME}-php-config
    spec:
      accessModes: 
      - ReadWriteOnce
      volumeMode: Filesystem
      resources:
        requests:
          storage: 1Gi
      storageClassName: ${STORAGE_CLASS_NAME}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ${NAME}-mariadb-data
    spec:
      accessModes: 
      - ReadWriteOnce
      volumeMode: Filesystem
      resources:
        requests:
          storage: 1Gi
      storageClassName: ${STORAGE_CLASS_NAME}
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        deploymentconfig: ${NAME}
      strategy:
        type: Rolling
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: ${NAME}
            deploymentconfig: ${NAME}
        spec:
          volumes:
          - name: ${NAME}-cache
            emptyDir: {}
          - name: ${NAME}-logs
            emptyDir: {}
          - name: ${NAME}-php-config
            persistentVolumeClaim:
              claimName: ${NAME}-php-config
          - name: ${NAME}-cache-unsubscribe
            emptyDir: {}
          - name: ${NAME}-apache-conf
            configMap:
              name: ${NAME}-apache-config
          containers:
            - env:
                - name: MAUTIC_DB_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: ${NAME}-db
                - name: MAUTIC_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: ${NAME}-db
                - name: MAUTIC_DB_NAME
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: ${NAME}-db
                - name: MAUTIC_DB_HOST
                  value: ${NAME}-db
                - name: MAUTIC_DB_PORT
                  value: "3306"
              image: >-
                image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/${NAME}:${IMAGE_TAG}
              imagePullPolicy: Always
              name: ${NAME}
              resources:
                cpu:
                  requests: 1000m
                  limits: 1500m
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - name: ${NAME}-apache-conf
                  mountPath: /etc/apache2/sites-enabled/000-default.conf
                  subPath: 000-default.conf
                - name: ${NAME}-apache-conf
                  mountPath: /etc/apache2/ports.conf
                  subPath: ports.conf
                - name: ${NAME}-cache
                  mountPath: /var/www/html/var/cache/
                - name: ${NAME}-logs
                  mountPath: /var/www/html/var/logs/
                - name: ${NAME}-php-config
                  mountPath: /var/www/html/app/config/
                - name: ${NAME}-cache-unsubscribe
                  mountPath: /var/www/html/app/../var/tmp/twig/
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
        app.openshift.io/vcs-ref: main
        app.openshift.io/vcs-uri: ${GIT_REPO}
        deployment.kubernetes.io/revision: '11'
        openshift.io/generated-by: OpenShiftWebConsole
      generation: 11
      labels:
        app: ${NAME}
        deploymentConfig: ${NAME}
        app.kubernetes.io/component: ${NAME}
        app.kubernetes.io/instance: ${NAME}
        app.kubernetes.io/part-of: ${NAME}-app
      name: ${NAME}
  - apiVersion: route.openshift.io/v1
    kind: Route
    spec:
      host: ${NAME}-${NAMESPACE}.${HOSTADDRESS}
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: ${NAME}
        weight: 100
      wildcardPolicy: None
    metadata:
      annotations:
        openshift.io/host.generated: 'true'
      labels:
        app: ${NAME}
        deploymentConfig: ${NAME}
        app.kubernetes.io/component: ${NAME}
        app.kubernetes.io/instance: ${NAME}
        app.kubernetes.io/part-of: ${NAME}-app
      name: ${NAME}
  - apiVersion: v1
    kind: Service
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: ${NAME}
      sessionAffinity: None
      type: ClusterIP
    metadata:
      annotations:
        app.openshift.io/vcs-ref: ${GIT_REF}
        app.openshift.io/vcs-uri: ${GIT_REPO}
        openshift.io/generated-by: OpenShiftWebConsole
      labels:
        app: ${NAME}
        deploymentConfig: ${NAME}
        app.kubernetes.io/component: ${NAME}
        app.kubernetes.io/instance: ${NAME}
        app.kubernetes.io/part-of: ${NAME}-app
      name: ${NAME} 
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      annotations:
        openshift.io/host.generated: 'true'
      labels:
        app: ${NAME}
        deploymentConfig: ${NAME}
        app.kubernetes.io/component: ${NAME}
        app.kubernetes.io/instance: ${NAME}
        app.kubernetes.io/part-of: ${NAME}-app
      name: ${NAME}-apache-config
    data:
      000-default.conf: |
        <VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        #ServerName www.example.com

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf
        </VirtualHost>
        # vim: syntax=apache ts=4 sw=4 sts=4 sr noet

      ports.conf: |
        # If you just change the port or add more ports here, you will likely also
        # have to change the VirtualHost statement in
        # /etc/apache2/sites-enabled/000-default.conf
        Listen 8080
        # vim: syntax=apache ts=4 sw=4 sts=4 sr noet

  - apiVersion: v1
    kind: Service
    spec:
      ports:
        - name: ${NAME}-db
          port: 3306
          protocol: TCP
          targetPort: 3306
      selector:
        name: ${NAME}-db
      sessionAffinity: None
      type: ClusterIP
    metadata:
      annotations:
        template.openshift.io/expose-uri: 'mysql://{.spec.clusterIP}:{.spec.ports[?(.name=="mariadb")].port}'
      labels:
        app: ${NAME}
        deploymentConfig: ${NAME}-db
        group: ${NAME}
      name: ${NAME}-db
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        name: ${NAME}-db
      strategy:
        activeDeadlineSeconds: 21600
        recreateParams:
          timeoutSeconds: 600
        resources: {}
        type: Recreate
      template:
        metadata:
          creationTimestamp: null
          labels:
            name: ${NAME}-db
        spec:
          containers:
            - env:
                - name: MYSQL_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: ${NAME}-db
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: ${NAME}-db
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-root-password
                      name: ${NAME}-db
                - name: MYSQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: ${NAME}-db
              image: registry.redhat.io/rhel8/mariadb-103
              imagePullPolicy: IfNotPresent
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 30
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 3306
                timeoutSeconds: 1
              name: mariadb
              ports:
                - containerPort: 3306
                  protocol: TCP
              readinessProbe:
                exec:
                  command:
                    - /bin/sh
                    - '-i'
                    - '-c'
                    - >-
                      MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u
                      $MYSQL_USER -D $MYSQL_DATABASE -e 'SELECT 1'
                failureThreshold: 3
                initialDelaySeconds: 5
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                limits:
                  memory: 512Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /var/lib/mysql/data
                  name: ${NAME}-mariadb-data
                - mountPath: /var/lib/mysql
                  name: ${NAME}-mariadb-docker
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - persistentVolumeClaim:
                claimName: ${NAME}-mariadb-data
              name: ${NAME}-mariadb-data
            - name: ${NAME}-mariadb-docker
              emptyDir: {}
      test: false
    metadata:
      annotations:
        app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"${NAME}"}]'
        template.alpha.openshift.io/wait-for-ready: 'true'
      generation: 2
      labels:
        deploymentConfig: ${NAME}-db
        template: mariadb-persistent-template
        group: ${NAME}
        app: ${NAME}
      name: ${NAME}-db
parameters:
- name: NAME
  displayName: name
  description: the value used to group components by a common name
  value: mautic
- name: GIT_REF
  displayName: Git Branch
  description: the git branch to build from
  value: main 
- name: GIT_REPO
  displayName: Git repository
  description: the git repo to build from
  value: https://github.com/patricksimonian/mautic-openshift
- name: NAMESPACE
  displayName: Namespace
  description: the namespace of the app
- name: HOSTADDRESS
  displayName: Host name
  description: The cluster host address
  value: apps.silver.devops.gov.bc.ca
- description: A name used for all objects
  displayName: IMAGE_TAG
  name: IMAGE_TAG
  required: true
- description: A name used for all objects
  displayName: STORAGE_CLASS_NAME
  name: STORAGE_CLASS_NAME
  required: true