kind: Template
apiVersion: v1
objects:
  - apiVersion: v1
    kind: Secret
    stringData:
      mysql_root_password: ${MYSQL_ROOT_PASSWORD}
    type: Opaque
    metadata:
      annotations:
        template.openshift.io/expose-mysql_root_password: '{.data[''mysql_root_password'']}'
      labels:
        component: secret
        app: ${NAME}
      name: ${NAME}-db
parameters:
# Test docker image params
- name: NAME
  displayName: name
  description: the value used to group components by a common name
# - name: DATABASE_USER
#   description: the database root user
#   displayName: Database Root Username
#   from: '[a-zA-Z0-9]{8}'
#   generate: expression
# - name: DATABASE_NAME
#   description: the database name
#   displayName: Database Name
#   from: '[a-zA-Z0-9]{8}'
#   generate: expression
# - name: DATABASE_USER_PASSWORD
#   description: The database user password
#   displayName: Database User Password
#   from: '[a-zA-Z0-9]{8}'
#   generate: expression
- name: MYSQL_ROOT_PASSWORD
  description: The database root password
  displayName: Database Root User Password
  from: '[a-zA-Z0-9]{8}'
  generate: expression